### ISSUE TITLE
Missing dependency. Error installing on grails 2.5.1

### ISSUE THREAD

**Issue by erbrito** [peh/grails-babel-asset-pipeline#1]
Error installing the plugin on grails 2.5.1. 
I added compile ":babel-asset-pipeline:1.3.1" to BuidConfig.groovy.
I try to lunch the project and the console shows:

Error |
Resolve error obtaining dependencies: Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.3.0 in grailsCentral (https://repo.grails.org/grails/plugins)
Error |
Resolve error obtaining dependencies: Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.3.0 in grailsCentral (https://repo.grails.org/grails/plugins) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.3.0 in grailsCentral (https://repo.grails.org/grails/plugins)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
    at grails.util.BuildSettings.doResolve(BuildSettings.groovy:513)
    at grails.util.BuildSettings.doResolve(BuildSettings.groovy)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
    at grails.util.BuildSettings$_getDefaultCompileDependencies_closure15.doCall(BuildSettings.groovy:503)
    at grails.util.BuildSettings$_getDefaultCompileDependencies_closure15.doCall(BuildSettings.groovy)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
    at grails.util.BuildSettings.getDefaultCompileDependencies(BuildSettings.groovy:496)
    at grails.util.BuildSettings.getCompileDependencies(BuildSettings.groovy:472)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.3.0 in grailsCentral (https://repo.grails.org/grails/plugins)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
    ... 9 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.3.0 in grailsCentral (https://repo.grails.org/grails/plugins)
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 11 more

Error |
Resolve error obtaining dependencies: Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.3.0 in grailsCentral (https://repo.grails.org/grails/plugins)
Error |
Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.3.0 in grailsCentral (https://repo.grails.org/grails/plugins)
|Run 'grails dependency-report' for further information.

**Comment by peh** [comment]
can you try to add 
`mavenRepo "http://dl.bintray.com/errbuddy/plugins"`
to you repos block in BuildConfig.groovy please and tell me if it works?

**Comment by erbrito** [comment]
It works! I added the mavenRepo and it installed the plugin.

Thanks,

Erick Brito

On Mon, Oct 5, 2015 at 2:33 PM, Philipp Eschenbach <notifications@github.com
